### ISSUE TITLE
HQ-RAIN Dataset

### ISSUE THREAD

**Issue by inakierregueab** [cschenxiang/HQ-RAIN#1]
Hello, are you expecting to upload the dataset in Google Drive or Dropbox? It will be super helpful. Thank you very much.

**Comment by cschenxiang** [comment]
> Hello, are you expecting to upload the dataset in Google Drive or Dropbox? It will be super helpful. Thank you very much.

Thanks for your suggestion. We have uploaded the data to Dropbox.

[TrainSet-Input]
https://www.dropbox.com/scl/fi/w8rry0qdirq8symd94e44/HQ-RAIN_train_input.zip?rlkey=kyldqs878l3x5kh3hafjwk1yj&dl=0

[TrainSet-Target]
https://www.dropbox.com/scl/fi/omf3k5rz2g2v2zgk2xq4c/HQ-RAIN_train_target.zip?rlkey=aj2ywnzjmyy435vq3yq1a0zxt&dl=0

[TestSet-Input]
https://www.dropbox.com/scl/fi/xx418hyb3eo7oj3obayv7/HQ-RAIN_test_input.zip?rlkey=3l7o115xt947fj1yzsscz503r&dl=0

**Comment by inakierregueab** [comment]
Thank you very much!!!
