### ISSUE TITLE
Regarding the issue of corrupted images in the dataset

### ISSUE THREAD

**Issue by weihua9217** [cschenxiang/HQ-RAIN#2]
Hello,

Thank you for your research and contributions. However, I recently downloaded the dataset (HQ-Rain-Test) you provided and found that one image (324.png) is not usable; it seems to be corrupted. Could you please help verify if there is an issue with this image? Additionally, I would like to ask if it is possible to provide a Dropbox download link, as I am unable to use Baidu Cloud for downloading. Thank you very much for your assistance !

**Comment by cschenxiang** [comment]
> Hello,
> 
> Thank you for your research and contributions. However, I recently downloaded the dataset (HQ-Rain-Test) you provided and found that one image (324.png) is not usable; it seems to be corrupted. Could you please help verify if there is an issue with this image? Additionally, I would like to ask if it is possible to provide a Dropbox download link, as I am unable to use Baidu Cloud for downloading. Thank you very much for your assistance !

Thank you for discovering the issue. We have just revised the link. In addition, we also provide a link to Google Cloud Drive: https://drive.google.com/file/d/1D54P0-wfhq0lcKdoy0Ly2FLukeFf8cGY/view?usp=sharing

**Comment by weihua9217** [comment]
Thank you for your response!
